spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1/lottery
    username: postgres
    password: postgres
  flyway:
   locations: classpath:/{vendor}
   enabled: true
#  h2:
#    console:
#      enabled: true
  jackson:
    default-property-inclusion: NON_NULL
